### ISSUE TITLE
does 'tap' this have the same shortcomings as filamentgoup/tappy?

### ISSUE THREAD

**Issue by gebrits** [pukhalski/tap#22]
[filamentgroup/tappy](https://github.com/filamentgroup/tappy) caveats (see docs at the bottom): 

- binding multiple handlers to the same element
- binding a handler to a child element when the parent element is already bound
- 'click' is not swallowed.

Does tap allow this?

**Comment by gebrits** [comment]
It seems that is does! Cheers.

**Comment by ezhlobo** [comment]
I was late... I wrote [filamentgroup/tappy](https://github.com/filamentgroup/tappy) examples before you closed issue :).

##### Binding multiple handlers to the same element:
http://jsbin.com/salacododi/1/edit?html,js,console,output
##### Binding a handler to a child element when the parent element is already bound:
http://jsbin.com/ginapoqida/1/edit?html,js,console,output
