### ISSUE TITLE
Expand taps from BODY to HTML

### ISSUE THREAD

**Issue by yoyurec** [pukhalski/tap#25]
When you use fixed width & `margin: 0 auto` for body in layout there is an issue:
Clicking on empty areas (target - **html**) doesn't not fire  `tap` event, b'cose they are not in listen scope (**body**).

![55194fff1ae737-17091547](https://cloud.githubusercontent.com/assets/137919/6897168/81e48e6c-d6fa-11e4-8016-024cb961a1b8.png)

Just replace `document.body` to `document.documentElement`!
https://github.com/pukhalski/tap/blob/master/dist/tap.js#L73
https://github.com/pukhalski/tap/blob/master/dist/tap.js#L141

**Comment by yoyurec** [comment]
https://github.com/pukhalski/tap/pull/26

**Comment by pukhalski** [comment]
Thanks, merged.
