### ISSUE TITLE
iPhone 6 support - Create demo/test page

### ISSUE THREAD

**Issue by montogeek** [pukhalski/tap#28]
Does Tap support iPhone 6 devices?

It would be great to have a demo page or something to test it quickly

Thanks!

**Comment by pukhalski** [comment]
Hey @montogeek, yes, Tap does support iPhone 6 running iOS 8+, of course. Honestly saying I am a user of iPhone 6 too. 

But I support the idea of having a landing page / test page.

**Comment by montogeek** [comment]
Great! Thanks!

**Comment by leifdejong** [comment]
@montogeek is this done?

**Comment by montogeek** [comment]
I dont think so

**Comment by ezhlobo** [comment]
:+1: 

@pukhalski will be useful page. Also we may use it for automated tests.
