### ISSUE TITLE
VoiceOver

### ISSUE THREAD

**Issue by leifdejong** [pukhalski/tap#29]
VoiceOver double tap has issue triggering the on tap event action handler. 

Running: iPhone 6 - iOS 8.1.2

**Comment by pukhalski** [comment]
Thanks, @leifdejong. A pretty valuable issue. Never thought about it.

Any ideas so far?

**Comment by leifdejong** [comment]
@pukhalski Yap so the workaround that I set up was to bind the element to a 'click' as well as a 'tap' and then write some logic to check if it's 'tap', suppress click, otherwise use the click. I have seen this issue on tappy, tap, and hammer. Seems like not a lot of people test VO. My recommendation would be to bind the 'click' when you bind 'tap' and then handle it internally. I will be working on a solution for hammer. Will share my code here once I am through.

**Comment by ezhlobo** [comment]
Tried to fix it: #30 

/cc @leifdejong @pukhalski

**Comment by leifdejong** [comment]
Looking good so far. Set up a code pen (http://codepen.io/anon/pen/doRpbq) and created a demo pull request (https://github.com/pukhalski/tap/pull/33)

**Comment by leifdejong** [comment]
VO seems to pick everything up

**Comment by pukhalski** [comment]
Cool! Gonna merge all PRs then.

**Comment by leifdejong** [comment]
@pukhalski :+1:
