### ISSUE TITLE
iOS9 tap is not working

### ISSUE THREAD

**Issue by Zanisimo** [pukhalski/tap#46]
In iOS9 window.propertyIsEnumerable('ontouchstart') and document.hasOwnProperty('ontouchstart') both return false and there are no event listeners added because of this. Issue is tested on iPhone6 and iPad air 2 with iOS9

In my implementation I changed test in eventMatrix to ('ontouchstart' in window || 'ontouchstart' in document), but I only support Andriod and iOS devices. I am not sure if this fix would work.

Please advise on better solution if it is needed.

**Comment by r00ger** [comment]
Same here. Doesn't work on iOS9 and suggested solution solves the problem.

**Comment by Altcore** [comment]
I have same problem and my fix: 
https://github.com/pukhalski/tap/pull/44

**Comment by squio** [comment]
Just a heads up that fix #44 indeed works (tested with ios 9.0.2, iPhone 5 and iPad 3)

**Comment by pukhalski** [comment]
Fixed in #44. Thanks, guys!

**Comment by BowlingX** [comment]
Hey, I just realized the fix is not in the distribution package. Could you rebuild and publish to npm?
Thank you :)

**Comment by pukhalski** [comment]
@ezhlobo
