### ISSUE TITLE
Android - CyanogenMod 12.1

### ISSUE THREAD

**Issue by MelchnerRoman** [pukhalski/tap#50]
Hey There,

i found out that tap.js itself is working but it disables all other click events on normal "a href" links on Android. So you can´t navigate between pages.

CyanogenMod 12.1 - i think its android version 5.

The tested Device is a Galaxy S4:
http://download.cyanogenmod.org/?type=snapshot&device=jfltexx

Cheers,
Roman

**Comment by ezhlobo** [comment]
@MelchnerRoman thanks for the issue. I'm trying to fix.

BTW It doesn't depend on the android's version... I reproduce it on android 4.

**Comment by ezhlobo** [comment]
It seems similar to #36

**Comment by ezhlobo** [comment]
@MelchnerRoman try new version 1.0.8, it has fixed the problem for me.

**Comment by ezhlobo** [comment]
Please reopen the issue if it’s still actual
