### ISSUE TITLE
Deploy 1.0.8 to NPM

### ISSUE THREAD

**Issue by mcat** [pukhalski/tap#56]
It looks like the latest version on NPM is 1.0.7 whereas the latest version on Github master branch is 1.0.7

**Comment by dryoma** [comment]
Bumping the request. @pukhalski any chance of doing that? ;)

**Comment by pukhalski** [comment]
@mcat, @dryoma, updated and pushed to NPM. Sorry for a huuuuge delay, I thought this library is not needed anymore, since most of the browsers have fixed this issue :)

**Comment by dryoma** [comment]
Thanks @pukhalski !

> I thought this library is not needed anymore, since most of the browsers have fixed this issue :)

Oh, but it is. Old safaris are still a thing in some projects' user bases (not a major one though).
